### PR TITLE
[NEW] GidoleRounded-Regular

### PR DESCRIPTION
**Pull request by GitBruno**
Added a rounded version. What do you think?

### CODE REVIEW

**Comment by larsenwork** [comment]
Niiiice, I'm terribly busy this week but will have a look at it this weekend. Thank you very much :+1:

**Comment by GitBruno** [comment]
No worries, let me know what you think.

I did notice some spacing issues, not sure how to best tackle this as I am not using the same software as you.

Bruno

**Comment by davelab6** [comment]
@larsenwork any chance to look at this? :)

**Comment by kroko** [comment]
@larsenwork Pardon for offt in this PR, but any thoughts on if Gidole project will be continued (weights, italics, altstyles such as this PR)? Thanks!

**Pull request closed without merging**
